---
title: "R Notebook"
output: html_notebook
---


```{r}
library(Seurat)
library(Signac)
```

```{r}
seurat.files <- list.files(path = '/data/proj/GCB_MB/bcd_CT/single-cell/results_archive/',pattern = 'Seurat_object.Rds',recursive = TRUE,full.names = TRUE)
seurat.files <- seurat.files[grep(pattern = '/bin_5000/',x = seurat.files)]
seurat.files
```


```{r}
brain.ls <- lapply(seurat.files,function(x){
  readRDS(file=x)
})

DimPlot(brain.ls[[1]])
DimPlot(brain.ls[[2]])

brain.ls[[1]]$antibody <- "H3K27me3"
brain.ls[[2]]$antibody <- "H3K27ac"


fragments <- list("H3K27me3"="/data/proj/GCB_MB/bcd_CT/single-cell/results/H3K27me3/bcdCT_MB21_01a/outs/fragments.tsv.gz",
                  "H3K27ac"="/data/proj/GCB_MB/bcd_CT/single-cell/results/H3K27ac/bcdCT_MB21_01b/outs/fragments.tsv.gz")


```

```{r}
library(ggplot2)

VlnPlot(brain.ls[[1]],'logUMI')
VlnPlot(brain.ls[[2]],'logUMI')
```


```{r}
# Rename cells
brain.ls <- lapply(brain.ls,function(x){
 new_cell_ids <- strsplit(colnames(x),"_")
 new_cell_ids <- lapply(new_cell_ids,function(y){
   y[length(y)]
 })
 RenameCells(x,new.names=new_cell_ids)
 })

common.cells <- lapply(brain.ls,function(x){
  colnames(x)
})
common.cells <- table(unlist(common.cells))


all.cells    <- unique(names(common.cells))
common.cells <- names(common.cells[common.cells==2])

samples <- unique(unname(unlist(lapply(brain.ls,function(x){x$sample}))))

all.cells.with.sampleID <- t(outer(samples,all.cells,paste,sep="_"))
colnames(all.cells.with.sampleID) <- names(fragments)

common.cells.with.sampleID <- t(outer(samples,common.cells,paste,sep="_"))
colnames(common.cells.with.sampleID) <- names(fragments)

head(all.cells.with.sampleID)
head(common.cells.with.sampleID)
```

```{r generate_new_matrix}
library(GenomicFeatures)

matrix.ls <- lapply(brain.ls,function(x){
  antibody = unname(x$antibody[1])
  
  fragments.x = fragments[[antibody]]
  fragments.object <- CreateFragmentObject(path = fragments.x,
                                           cells = all.cells.with.sampleID[,antibody],
                                           validate.fragments = TRUE,verbose = TRUE)
  
  genome <- getChromInfoFromUCSC('mm10')
  genome <- setNames(object = genome$length, nm = genome$chrom)
  
  matrix.x <- GenomeBinMatrix(fragments = fragments.object,
                  genome = genome[1:20],
                  cells = all.cells.with.sampleID[,antibody],
                  binsize = 5000,
                  verbose = TRUE)
  rownames(matrix.x) <- paste0(antibody,'-',rownames(matrix.x))
  colnames(matrix.x) <- unlist(lapply(strsplit(colnames(matrix.x),"_"),function(x){x[length(x)]}))
  return(matrix.x)
})


matrix.merged <- do.call('rbind',matrix.ls)
```

```{r}

brain <- CreateSeuratObject(counts = matrix.merged,assay = 'bins_5000_merged')

brain[['bins_5000_H3K27me3']] <- CreateAssayObject(counts = matrix.ls[[1]])
brain[['bins_5000_H3K27ac']] <- CreateAssayObject(counts = matrix.ls[[2]])


brain <- SetIdent(brain,cells= names(brain.ls[[2]]@active.ident), value = brain.ls[[2]]@active.ident)
```


```{r}
assay  = 'bins_5000_H3K27ac'
DefaultAssay(brain) <- assay
ndim=50

brain <- RunTFIDF(brain,assay = assay)
brain <- FindTopFeatures(brain,assay = assay)
  
brain <- RunSVD(
  object = brain,
  assay = assay,
  reduction.key = 'LSI_',
  reduction.name = 'lsi',
  n = 50
)
  
brain <- RunUMAP(
  object = brain,
  reduction = 'lsi',
  dims = 2:ndim,
  reduction.name = 'UMAP_1'
)
  
p1 <- DimPlot(brain,label=TRUE,reduction = 'UMAP_1')

```

```{r}
assay  = 'bins_5000_H3K27me3'
DefaultAssay(brain) <- assay
ndim=15

brain <- RunTFIDF(brain,assay = assay)
brain <- FindTopFeatures(brain, assay = assay)
  
brain <- RunSVD(
  object = brain,
  assay = assay,
  reduction.key = 'LSI_',
  reduction.name = 'lsi',
  n = 50
)
  
brain <- RunUMAP(
  object = brain,
  reduction = 'lsi',
  dims = 2:ndim,
  reduction.name = 'UMAP_2'
)
  
p2 <- DimPlot(brain,label=TRUE,reduction = 'UMAP_2')
p2
```



```{r}
assay  = 'bins_5000_merged'
DefaultAssay(brain) <- assay
ndim=50

brain <- RunTFIDF(brain,assay = assay)
brain <- FindTopFeatures(brain,assay = assay)
  
brain <- RunSVD(
  object = brain,
  assay = assay,
  reduction.key = 'LSI_',
  reduction.name = 'lsi',
  n = 50
)
  
brain <- RunUMAP(
  object = brain,
  reduction = 'lsi',
  dims = 2:ndim
)
  
p3 <- DimPlot(brain,label=TRUE,reduction = 'UMAP3')


```

```{r plot, fig.width=12,fig.height=4}
p1+p2+p3
```





################






```{r Rename_features, eval=FALSE}
brain.ls <- lapply(brain.ls,function(x){
  for(assay in names(x@assays)){
    matrix.x <- x[[assay]]@counts
    rownames(matrix.x) <- paste0(x$antibody[1],"-",rownames(matrix.x))
    x[[assay]] <- CreateAssayObject(matrix.x)
  }
  x
})


```



```{r rename_cells, eval=FALSE}
# Rename cells
brain.ls <- lapply(brain.ls,function(x){
 new_cell_ids <- strsplit(colnames(x),"_")
 new_cell_ids <- lapply(new_cell_ids,function(y){
   y[length(y)]
 })
 RenameCells(x,new.names=new_cell_ids)
 })

common.cells <- lapply(brain.ls,function(x){
  colnames(x)
})
common.cells <- table(unlist(common.cells))
common.cells <- names(common.cells[common.cells==2])
```




```{r assays, eval=FALSE}
brain.ls <- lapply(brain.ls,function(x){
  x <- RenameAssays(object = x,GA=paste0("GA_",x$antibody[1]))
  x <- RenameAssays(object = x,PA=paste0("PA_",x$antibody[1]))
  x <- RenameAssays(object = x,peaks=paste0("peaks_",x$antibody[1]))
  x <- RenameAssays(object = x,bins_5000=paste0("bins_5000_",x$antibody[1]))
})


brain.merged <- brain.ls[[1]][,common.cells]

for (seurat_object in brain.ls){
  seurat_object <- seurat_object[,common.cells]
  all_assays <- names(seurat_object@assays)
  for(assay in all_assays){
    brain.merged[[assay]] <- seurat_object[[assay]]
  }
}

```

```{r assays2, eval=FALSE}
for(assay in list("GA","PA","peaks","bins_5000")){
  all_assays <- names(brain.merged@assays)
  assays <- all_assays[grep(pattern = assay,x = all_assays)]
  assays.ls <- lapply(assays,function(x){
    brain.merged[[x]]@counts
  })
  assays.merged <- do.call('rbind',assays.ls)
  brain.merged[[paste0(assay,"_merged")]] <- CreateAssayObject(assays.merged)
}

brain.merged@assays

```


