---
title: "R Notebook"
output: html_notebook
params:
  metadata:
    - /data/proj/GCB_MB/bcd_CT/single-cell/results/bcdCT_MB21_03/H3K27ac_ATAGAGGC/cell_picking/metadata.csv
    - /data/proj/GCB_MB/bcd_CT/single-cell/results/bcdCT_MB21_03/H3K27me3_CCTATCCT/cell_picking/metadata.csv
    
---

```{r libraries}
library(mclust)
library(dplyr)
library(ggplot2)
library(GGally)
```

```{r pick_cells_function}
pick_cells_MB <- function(log_unique_reads, frip){
  library(mclust)
  
  d <- as.data.frame(cbind(log_unique_reads,frip))
  d.model <- Mclust(d,3)
  d$class <- d.model$classification
  top.cluster <- d %>% group_by(class) %>% summarise(mean(log_unique_reads)) %>% top_n(1) %>% dplyr::select(class)
  top.cluster <- as.character(top.cluster)

  d$pass_model <- FALSE
  d$pass_model[d$class == top.cluster] <- TRUE
  return(d)
}

```


```{r pick_cells}
modalities <- params$metadata

d.ls <- lapply(modalities,function(x){
  d <- read.csv(file=x)
  return(d)
})

lapply(d.ls,function(x){
  ggplot(data=x, aes(x=all_unique_MB,y=peak_ratio_MB))  + 
    scale_x_log10() +
    geom_point(aes(col=passedMB),size=0.1) + 
    geom_density2d(col='black') + ggtitle(unique(x$modality))
  })

```

```{r plot_logUMI_scatter}
logUMI.ls <- lapply(d.ls,function(x){
  return(x[,c('logUMI','barcode','passedMB')])
})

logUMI.df <- logUMI.ls %>% purrr::reduce(full_join, by = "barcode")
rownames(logUMI.df) <- logUMI.df$barcode
logUMI.df.plot          <- logUMI.df[,grepl(pattern = 'logUMI',colnames(logUMI.df))]

logUMI.df.pass  <- logUMI.df[,grepl(pattern = 'passedMB',colnames(logUMI.df))]
logUMI.df.pass[is.na(logUMI.df.pass)] <- FALSE

logUMI.df.plot$pass_any <- as.logical(rowSums(logUMI.df.pass))

ggpairs(data=logUMI.df.plot,aes(color=pass_any),lower = list(continuous = wrap("points", alpha = 1, size=0.1))) 
```








