---
title: "R Notebook"
output: html_notebook
params:
  seurat: "/data/proj/GCB_MB/bcd_CT/single-cell/results/multiple_modalities/ATAC_H3K27ac_H3K27me3/seurat_multimodal/peaks/Seurat_object.Rds"
  output: "/data/proj/GCB_MB/bcd_CT/single-cell/results/multimodal_data/WNN/seurat/Seurat_object_WNN.Rds"
---


```{r}

library(Seurat)
library(Signac)
library(ggplot2)
library(dplyr)
library(gridExtra)
set.seed(1234)

```

```{r, fig.width=12,fig.height=4}
seurat <- readRDS(file=params$seurat)

p1 <- DimPlot(seurat[[1]],label=TRUE) + NoLegend() + ggtitle(unique(seurat[[1]]$modality))
p2 <- DimPlot(seurat[[2]],label=TRUE) + NoLegend() + ggtitle(unique(seurat[[2]]$modality))
p3 <- DimPlot(seurat[[3]],label=TRUE) + NoLegend() + ggtitle(unique(seurat[[3]]$modality))
p1+p2+p3
```


```{r}
common.cells <- Cells(seurat[[4]])

modalities <- names(seurat)
modalities <- modalities[modalities!='merged']

for(x in modalities){
  seurat[[x]] <- seurat[[x]][,common.cells]
  seurat[['merged']][[paste0('peaks_',x)]] <- seurat[[x]][['peaks']]
  seurat[['merged']][[paste0('GA_',x)]] <- seurat[[x]][['GA']]
}

seurat.wnn <- seurat[['merged']]

for(x in modalities){
  DefaultAssay(seurat.wnn) <- paste0('peaks_',x)
  seurat.wnn <- RunTFIDF(seurat.wnn) %>% FindTopFeatures() %>% RunSVD(reduction.name = paste0(x,'_lsi'))
}




seurat.wnn <- FindMultiModalNeighbors(
  seurat.wnn, reduction.list = list("ATAC_lsi","H3K27ac_lsi", "H3K27me3_lsi"), 
  dims.list = list(2:30,2:50, 2:50), modality.weight.name = "histone.weight",k.nn = 10
)

seurat.wnn <- RunUMAP(seurat.wnn, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
seurat.wnn <- FindClusters(seurat.wnn, graph.name = "wsnn", algorithm = 3, resolution = 0.8, verbose = FALSE)


FeaturePlot(seurat.wnn,'peaks_ATAC.weight',min.cutoff = 0.2,max.cutoff = 0.6) + scale_color_viridis_c()
FeaturePlot(seurat.wnn,'peaks_H3K27ac.weight',min.cutoff = 0.2,max.cutoff = 0.6) + scale_color_viridis_c()
FeaturePlot(seurat.wnn,'peaks_H3K27me3.weight',min.cutoff = 0.2,max.cutoff = 0.6) + scale_color_viridis_c()
DimPlot(seurat.wnn,label=TRUE)
```


```{r, fig.width=15,fig.height=15}
for(x in modalities){
  for(y in modalities){
    seurat[[y]] <- AddMetaData(seurat[[y]],seurat[[x]]$idents_L3,col.name = paste0('idents_L3_',x))
  }
}

p<- list()
for(y in modalities)
  for(x in modalities){
    p[[y]][[x]] <- DimPlot(seurat[[y]],label=TRUE,repel=TRUE,group.by=paste0('idents_L3_',x)) + NoLegend()
  }

p <- purrr::reduce(p,c)
library(gridExtra)
do.call('grid.arrange',p)
```




```{r,fig.width=20,fig.height=5}
seurat.wnn <- AddMetaData(seurat.wnn,seurat[['H3K27ac']]$idents_short,col.name = 'H3K27ac_cluster_idents')
p2 <- DimPlot(seurat.wnn,group.by='H3K27ac_cluster_idents',label=TRUE,repel=TRUE) + NoLegend()

seurat.wnn <- AddMetaData(seurat.wnn,seurat[['H3K27me3']]$idents_short,col.name = 'H3K27me3_cluster_idents')
p3 <- DimPlot(seurat.wnn,group.by='H3K27me3_cluster_idents',label=TRUE,repel=TRUE) + NoLegend()

seurat.wnn <- AddMetaData(seurat.wnn,seurat[['ATAC']]$idents_short,col.name = 'ATAC_cluster_idents')
p1 <- DimPlot(seurat.wnn,group.by='ATAC_cluster_idents',label=TRUE,repel=TRUE) + NoLegend()

p4 <-  DimPlot(seurat.wnn,group.by='seurat_clusters',label=TRUE,repel=TRUE) + NoLegend() + ggtitle("WNN clusters")

grid.arrange(p1,p2,p3,p4, nrow=1)
```


`
```{r}
VlnPlot(seurat.wnn, features = "peaks_H3K27ac.weight", sort = TRUE, pt.size = 0.1,group.by="H3K27me3.idents_L1")  + NoLegend()
VlnPlot(seurat.wnn, features = "peaks_H3K27me3.weight", sort = TRUE, pt.size = 0.1,group.by="H3K27me3.idents_L1")  + NoLegend() 
VlnPlot(seurat.wnn, features = "peaks_ATAC.weight", sort = TRUE, pt.size = 0.1,group.by="H3K27me3.idents_L1")   + NoLegend()

VlnPlot(seurat.wnn, features = "peaks_H3K27ac.weight", sort = TRUE, pt.size = 0.1,group.by="H3K27ac.idents_short")  + NoLegend()
VlnPlot(seurat.wnn, features = "peaks_H3K27me3.weight", sort = TRUE, pt.size = 0.1,group.by="H3K27ac.idents_short")  + NoLegend() 
VlnPlot(seurat.wnn, features = "peaks_ATAC.weight", sort = TRUE, pt.size = 0.1,group.by="H3K27ac.idents_short")   + NoLegend()

```

```{r,fig.width=12,fig.height=6}
wnn.idents <- seurat.wnn@active.ident

seurat[1:3] <- lapply(seurat[1:3],function(x){
  AddMetaData(x,wnn.idents,col.name = 'wnn.idents')
})

lapply(seurat[1:3],function(x){
  p1 <- DimPlot(x,group.by='idents_L3',label=TRUE,repel=TRUE) + NoLegend()
  p2 <- DimPlot(x,group.by = 'wnn.idents',label=TRUE,repel=TRUE) + NoLegend()
  p1+p2
})
```

```{r, fig.width=12,fig.height=4}
p1 <- DimPlot(seurat.wnn,group.by = 'ATAC.idents_short',label=TRUE) + NoLegend()
p2 <- DimPlot(seurat.wnn,group.by = 'H3K27ac.idents_short',label=TRUE) + NoLegend()
p3 <- DimPlot(seurat.wnn,group.by = 'H3K27me3.idents_short',label=TRUE) + NoLegend()
p4 <- DimPlot(seurat.wnn,label=TRUE) + NoLegend()
p1+p2+p4
```


```{r rename_WNN_L1, fig.width=8,fig.height=4}

idents_L1 <- c(
  '0' = 'Astroependymal',
  '1' = 'Astroependymal',
  '2' = 'Neurons',
  '3' = 'Vascular',
  '4' = 'Oligodendrocytes',
  '5' = 'Immune',
  '6' = 'Vascular',
  '7' = 'Astroependymal',
  '8' = 'Neurons',
  '9' = 'Oligodendrocytes',
  '10' = 'Astroependymal',
  '11' = 'Olfactory ensheating cells',
  '12' = 'Immune',
  '13' = 'Vascular',
  '14' = 'Neurons',
  '15' = 'Neurons',
  '16' = 'Vascular',
  '17' = 'Vascular',
  '18' = 'Astroependymal',
  '19' = 'Neurons',
  '20' = 'Astroependymal',
  '21' = 'Neurons',
  '22' = 'Neurons',
  '23' = 'Vascular',
  '24' = 'Astroependymal',
  '25' = 'Neurons'
)

seurat.wnn                 <- RenameIdents(seurat.wnn,idents_L1)
seurat.wnn$idents_L1    <- seurat.wnn@active.ident
seurat.wnn                 <- SetIdent(seurat.wnn,cells = names(seurat.wnn$seurat_clusters), value = seurat.wnn$seurat_clusters)

p1 <- DimPlot(seurat.wnn,label=TRUE,group.by = 'idents_L1') + NoLegend()
p2 <- DimPlot(seurat.wnn,label=TRUE, group.by = 'seurat_clusters') + NoLegend()

p1+p2

```


```{r rename_WNN_L2, fig.width=8,fig.height=4}

idents_L2 <- c(
  '0' = 'Astrocytes',
  '1' = 'Astrocytes',
  '2' = 'Neurons_Excitatory',
  '3' = 'Vascular_endothelial_cells',
  '4' = 'Mature_oligodendrocytes',
  '5' = 'Microglia',
  '6' = 'Vascular_endothelial_cells',
  '7' = 'Bergman_glia',
  '8' = 'Inhibitory_neurons',
  '9' = 'Oligodendrocyte_progenitor_cells',
  '10' = 'Radial_glial_cells',
  '11' = 'Olfactory_ensheating_cells',
  '12' = 'Macrophages',
  '13' = 'Pericytes',
  '14' = 'Inhibitory_neurons',
  '15' = 'Inhibitory_neurons',
  '16' = 'Choroid_plexus_epithelial_cells',
  '17' = 'Vascular_leptomeningeal_cells',
  '18' = 'Astrocytes_3',
  '19' = 'Inhibitory_neurons',
  '20' = 'Astrocytes_4',
  '21' = 'Neurons_Excitatory',
  '22' = 'Neurons_Excitatory',
  '23' = 'Arachnoid_bareer_cells',
  '24' = 'Ependymal_cells',
  '25' = 'Inhibitory_neurons'
)

seurat.wnn                 <- RenameIdents(seurat.wnn,idents_L2)
seurat.wnn$idents_L2    <- seurat.wnn@active.ident
seurat.wnn                 <- SetIdent(seurat.wnn,cells = names(seurat.wnn$seurat_clusters), value = seurat.wnn$seurat_clusters)

p1 <- DimPlot(seurat.wnn,label=TRUE,group.by = 'idents_L2') + NoLegend()
p2 <- DimPlot(seurat.wnn,label=TRUE, group.by = 'seurat_clusters') + NoLegend()

p1+p2

```



```{r rename_WNN_L3, fig.width=8,fig.height=4}

idents_L3 <- c(
  '0' = 'Astrocytes_non-telencephalon',
  '1' = 'Astrocytes_telencephalon',
  '2' = 'Neurons_Excitatory_1',
  '3' = 'Vascular_endothelial_cells_1',
  '4' = 'Mature_oligodendrocytes',
  '5' = 'Microglia',
  '6' = 'Vascular_endothelial_cells_2',
  '7' = 'Bergman_glia',
  '8' = 'Inhibitory_neurons_1',
  '9' = 'Oligodendrocyte_progenitor_cells',
  '10' = 'Radial_glial_cells',
  '11' = 'Olfactory_ensheating_cells',
  '12' = 'Macrophages',
  '13' = 'Pericytes',
  '14' = 'Inhibitory_neurons_2',
  '15' = 'Inhibitory_neurons_3',
  '16' = 'Choroid_plexus_epithelial_cells',
  '17' = 'Vascular_leptomeningeal_cells',
  '18' = 'Astrocytes_3',
  '19' = 'Inhibitory_neurons_4',
  '20' = 'Astrocytes_4',
  '21' = 'Neurons_Excitatory_2',
  '22' = 'Neurons_Excitatory_3',
  '23' = 'Arachnoid_bareer_cells',
  '24' = 'Ependymal_cells',
  '25' = 'Inhibitory_neurons_5'
)

seurat.wnn                 <- RenameIdents(seurat.wnn,idents_L3)
seurat.wnn$idents_L3    <- seurat.wnn@active.ident
seurat.wnn                 <- SetIdent(seurat.wnn,cells = names(seurat.wnn$seurat_clusters), value = seurat.wnn$seurat_clusters)

p1 <- DimPlot(seurat.wnn,label=TRUE,group.by = 'idents_L3') + NoLegend()
p2 <- DimPlot(seurat.wnn,label=TRUE, group.by = 'seurat_clusters') + NoLegend()

p1+p2

```



```{r rename_WNN_short, fig.width=8,fig.height=4}

idents_short <- c(
  '0' = 'AST_NT',
  '1' = 'AST_TE',
  '2' = 'EXC1',
  '3' = 'VEC1',
  '4' = 'MOL',
  '5' = 'MGL',
  '6' = 'VEC2',
  '7' = 'BG',
  '8' = 'INH1',
  '9' = 'OPC',
  '10' = 'RGC',
  '11' = 'OEC',
  '12' = 'MAC',
  '13' = 'PER',
  '14' = 'INH2',
  '15' = 'INH3',
  '16' = 'CHP',
  '17' = 'VLMC',
  '18' = 'AST3',
  '19' = 'INH4',
  '20' = 'AST4',
  '21' = 'EXC2',
  '22' = 'EXC3',
  '23' = 'ABC',
  '24' = 'EPE',
  '25' = 'INH5'
)

seurat.wnn                 <- RenameIdents(seurat.wnn,idents_short)
seurat.wnn$idents_short    <- seurat.wnn@active.ident
seurat.wnn                 <- SetIdent(seurat.wnn,cells = names(seurat.wnn$seurat_clusters), value = seurat.wnn$seurat_clusters)

p1 <- DimPlot(seurat.wnn,label=TRUE,group.by = 'idents_short') + NoLegend()
p2 <- DimPlot(seurat.wnn,label=TRUE, group.by = 'seurat_clusters') + NoLegend()

p1+p2

```











```{r export}
saveRDS(object = seurat.wnn,file = params$output)

```



```{r noWNN_just_merge}
seurat.noWNN <- readRDS(file=params$seurat)

DefaultAssay(seurat.noWNN[['merged']]) <- 'peaks'
seurat.noWNN[['merged']] <- seurat.noWNN[['merged']] %>% RunTFIDF() %>% FindTopFeatures() %>% RunSVD() 

seurat.noWNN[['merged']] <- RunUMAP(object = seurat.noWNN[['merged']], dims=2:50,reduction = 'lsi')
seurat.noWNN[['merged']] <- FindNeighbors(seurat.noWNN[['merged']],reduction = 'lsi',dims = 2:50) %>% FindClusters()



for(x in modalities){
  seurat.noWNN[['merged']] <- AddMetaData(seurat.noWNN[['merged']],metadata = seurat.noWNN[[x]]$idents_L3,col.name = paste0(x,'_idents_short'))
}

DimPlot(seurat.noWNN[['merged']],label=TRUE) + NoLegend()
lapply(modalities,function(x){
  DimPlot(seurat.noWNN[['merged']],group.by=paste0(x,'_idents_short'),label=TRUE,repel=TRUE) + NoLegend()
})

```
