samples:
  bcdCT_MB21_02:
    fastq_path:
      /data/proj/GCB_MB/bcd_CT/single-cell/fastq/P23209/P23209/P23209_1001/     # Modify path to fastq files here
    barcodes:
      ATAC: TATAGCCT
      H3K27ac: ATAGAGGC
      H3K27me3: CCTATCCT
    GFP: unsorted
    Age: P19

  bcdCT_MB21_03:
    fastq_path:
      /data/proj/GCB_MB/bcd_CT/single-cell/fastq/P23209/P23209/P23209_1002/       # Modify path to fastq files here
    barcodes:
      H3K27ac: ATAGAGGC
      H3K27me3: CCTATCCT
    GFP: unsorted
    Age: P19

  bcdCT_MB21_04:
    fastq_path:
      /data/proj/GCB_MB/bcd_CT/single-cell/fastq/P24004/P24004_1001/          # Modify path to fastq files here
    barcodes:
      ATAC: TATAGCCT
      H3K27ac: ATAGAGGC
      H3K27me3: CCTATCCT
    GFP: unsorted
    Age: P19

  bcdCT_MB21_05:
      fastq_path:
        /data/proj/GCB_MB/bcd_CT/single-cell/fastq/P24004/P24004_1002/       # Modify path to fastq files here
      barcodes:
        H3K27ac: ATAGAGGC
        H3K27me3: CCTATCCT
      GFP: unsorted
      Age: P19

general:
  genome: mm10
  tempdir: /data/proj/GCB_MB/tmp                                                          # Modify path here to tmp folder
  binwidth: [5000,10000,25000,50000,100000]
  conda_env: bcdCT                                                                        # Specify conda env name here
  cellranger_ref: /data/ref/cellranger-atac/refdata-cellranger-atac-mm10-2020-A-2.0.0/    # Modify path here to cellranger reference folder

nbiotech_data:  # nothing needed to change here
  url:
    bigwig: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE157nnn/GSE157637/suppl/GSE157637_bigwig.tar.gz
    fragments: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE157nnn/GSE157637/suppl/GSE157637_modified_fragments_file_cellranger.tar.gz
    seurat: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE157nnn/GSE157637/suppl/GSE157637_Seurat_v3_object.tar.gz
  samples:
    H3K27ac_N1:
      SRR12607042
      SRR12607043
    H3K27ac_N2:
      SRR12607044
      SRR12607045
    H3K27me3_N1:
      SRR12607034
      SRR12607035
    H3K27me3_N2:
      SRR12607036
      SRR12607037
    H3K27me3_N3:
      SRR12607038
      SRR12607039
    H3K27me3_N4:
      SRR12607040
      SRR12607041





