---
title: "R Notebook"
output: html_notebook
params:
  out_prefix: "/data/proj/GCB_MB/bcd_CT/single-cell/results/"
---


```{r}
library(Seurat)
library(Signac)
library(ggplot2)
library(ggthemes)
library(purrr)
set.seed(1234)

dir.create(paste0(params$out_prefix,'/figures/figure_4/'))
```

```{r, fig.width=8,fig.height=8}
seurat.wnn <- readRDS(file=paste0(params$out_prefix,'/multimodal_data/WNN/seurat/Seurat_object_WNN.Rds'))
seurat.ls  <- readRDS(file=paste0(params$out_prefix,'/multiple_modalities/ATAC_H3K27ac_H3K27me3/seurat_multimodal/peaks/Seurat_object.Rds'))

seurat.ls <- lapply(seurat.ls, function(x){
  x <- x[,Cells(seurat.wnn)]
  x <- AddMetaData(x,seurat.wnn$idents_short,col.name='WNN.idents_short')
  x
})

p1 <- DimPlot(seurat.wnn,group.by='idents_short',label=TRUE) + NoLegend() + ggtitle("WNN")
p2 <- DimPlot(seurat.wnn,group.by='ATAC.idents_short',label=TRUE) + NoLegend() + ggtitle("ATAC-seq")
p3 <- DimPlot(seurat.wnn,group.by='H3K27ac.idents_short',label=TRUE) + NoLegend() + ggtitle("H3K27ac")
p4 <- DimPlot(seurat.wnn,group.by='H3K27me3.idents_short',label=TRUE) + NoLegend() + ggtitle("H3K27me3")

p1 + p2 + p3 + p4 

p1 <- DimPlot(seurat.wnn,group.by='idents_short',label=TRUE) + NoLegend() + ggtitle("WNN")
p2 <- DimPlot(seurat.ls[[1]],group.by='WNN.idents_short',label=TRUE) + NoLegend() + ggtitle("ATAC-seq")
p3 <- DimPlot(seurat.ls[[2]],group.by='WNN.idents_short',label=TRUE) + NoLegend() + ggtitle("H3K27ac")
p4 <- DimPlot(seurat.ls[[3]],group.by='WNN.idents_short',label=TRUE) + NoLegend() + ggtitle("H3K27me3")

p1 + p2 + p3 + p4 

ggsave(plot= p1+p2+p3+p4,filename = paste0(params$out_prefix,'/figures/figure_4/WNN_UMAP.pdf'),width=12,height=12)

```

```{r, fig.width=20,fig.height=20}
library(ggalluvial)

modalities <- c('ATAC.','H3K27ac.','H3K27me3.','')



idents.ls <- lapply(modalities, function(m){
  df         <- data.frame('ident' = seurat.wnn@meta.data[,paste0(m,'idents_short')],
                           'barcode' = rownames(seurat.wnn@meta.data),
                           'modality' = m,
                           'Freq' = 1)
  df$modality[df$modality == ''] <- 'wnn'
  df$modality <- gsub('\\.','',df$modality)
  # levels(df$ident) <- sort(levels(df$ident))
  df <- df[order(df$ident),]
  return(df)

})

idents.df <- purrr::reduce(idents.ls,rbind)


ggplot(data=idents.df, aes(x = modality, stratum = ident, alluvium = barcode, y = Freq, fill = ident, label = ident)) +
  scale_x_discrete(expand = c(.1, .1)) +
  geom_flow(alpha=0.8) +
  geom_stratum(alpha = 1) +
  geom_text(stat = "stratum", size = 5) +
  theme_minimal()+
  theme(legend.position = "none") 
 
ggsave(filename=paste0(params$out_prefix,'/figures/figure_4/allevium_WNN.pdf'),width=10,height=14)
```
```{r}
library(ChIPpeakAnno)

top.features.ls <- lapply(seurat.ls[1:3],function(seurat){
  top.features <- apply(Loadings(seurat,reduction = 'lsi')[,2:50],2,function(x){
    top    <- x[x > quantile(x,0.98)]
    bottom <- x[x < quantile(x,0.02)]
    return(c(names(top),names(bottom)))
    })
  
  top.features <- as.character(top.features)
  top.features <- StringToGRanges(top.features)
  top.features$modality <- unique(seurat$modality)
  return(top.features)
})

top.features.ls <- lapply(top.features.ls,unique)
gr <- c(top.features.ls[[1]],top.features.ls[[2]],top.features.ls[[3]])
grl <- splitAsList(gr, gr$modality)

pdf(file=paste0(params$out_prefix,'/figures/figure_4/overlap_Venn.pdf'),width = 5,height = 5)
res <- makeVennDiagram(Peaks=grl, NameOfPeaks=names(grl))
dev.off()



```


```{r, fig.width=8,fig.height=8}
seurat.ls <- readRDS(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multiple_modalities/ATAC_H3K27ac_H3K27me3/seurat_multimodal/peaks/Seurat_object.Rds')
# markers <- read.csv(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multimodal_data/single_modality/H3K27ac/seurat/peaks/markers/idents_short/markers.csv')


# DimPlot(seurat.ls[[3]],group.by='idents_short',label=T) + NoLegend()

seurat.ls.small <- lapply(seurat.ls[1:3],function(x){
  x <- x[,x$idents_short %in% c("AST_TE","AST_NT")]
  x
})


markers.ls <- lapply(seurat.ls.small,FindAllMarkers)


features.ls = list("ATAC" = "chr12-49372226-49402169","H3K27ac" = "chr12-49371935-49403257","H3K27me3"="chr12-49370426-49407415")

FeaturePlotPaired <- function(seurat.ls,features.ls, max.cutoff =2){
  emb.ls <- lapply(names(seurat.ls),function(x){
    seurat.x   <- seurat.ls[[x]]
    embeddings <- scale(seurat.x@reductions[['umap']]@cell.embeddings)
    if(x=='H3K27ac')  {embeddings[,1] <- embeddings[,1] + 10}
    if(x=='H3K27me3') {embeddings[,1] <- embeddings[,1] + 20; embeddings[,2] <- -embeddings[,2]}
    score      <- GetAssayData(object = seurat.x)[features.ls[[x]],]
    to.plot    <- as.data.frame(cbind(embeddings,score))
    to.plot$modality <- x
    to.plot$cluster  <-seurat.ls[[x]]$idents_short[rownames(to.plot)] 
    to.plot$cell_barcode <- rownames(to.plot)
    to.plot$score[to.plot$score > max.cutoff] <- max.cutoff
    return(to.plot)
  })
  
}


data.ls <- FeaturePlotPaired(seurat.ls.small, features.ls,max.cutoff = 10)
data.df <- purrr::reduce(data.ls,rbind)

connections <- sample(data.ls[[1]]$cell_barcode,500)

# ggplot(data.df,aes(x=UMAP_1,y=UMAP_2)) +
#   geom_point(aes(col=cluster),size=0.1) +
#   geom_line(aes(group=cell_barcode,col=cluster),alpha=0.01) +
#   theme(panel.grid = element_blank()) #+ scale_color_viridis_c()

theme_set(theme_minimal())
col_pal <- c(viridis_pal(option = 'B')(20))

ggplot(data.df,aes(x=UMAP_1,y=UMAP_2)) +
  geom_point(aes(col=score),size=0.4) +
  geom_line(aes(group=cell_barcode),alpha=0.04,size=0.2) +
  theme(panel.grid = element_blank()) + scale_color_gradientn(colours = col_pal,limits=c(1,3)) + coord_cartesian(ylim=c(-3,3))
ggsave(paste0(params$out_prefix,'/figures/figure_4/Foxg1_UMAP_connected.pdf'),width=8,height = 8 )
```




```{r Lhx2, fig.width=8,fig.height=8}
seurat.ls <- readRDS(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multiple_modalities/ATAC_H3K27ac_H3K27me3/seurat_multimodal/peaks/Seurat_object.Rds')
# markers <- read.csv(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multimodal_data/single_modality/H3K27ac/seurat/peaks/markers/idents_short/markers.csv')


# DimPlot(seurat.ls[[3]],group.by='idents_short',label=T) + NoLegend()

seurat.ls.small <- lapply(seurat.ls[1:3],function(x){
  x <- x[,x$idents_short %in% c("AST_TE","AST_NT")]
  x
})


# markers.ls <- lapply(seurat.ls.small,FindAllMarkers)


features.ls = list("ATAC"    = "chr2-38346609-38360393",
                   "H3K27ac" = "chr2-38346331-38368102",
                   "H3K27me3"="chr2-38332755-38368139")

FeaturePlotPaired <- function(seurat.ls,features.ls, max.cutoff =2){
  emb.ls <- lapply(names(seurat.ls),function(x){
    seurat.x   <- seurat.ls[[x]]
    embeddings <- scale(seurat.x@reductions[['umap']]@cell.embeddings)
    if(x=='H3K27ac')  {embeddings[,1] <- embeddings[,1] + 10}
    if(x=='H3K27me3') {embeddings[,1] <- embeddings[,1] + 20; embeddings[,2] <- -embeddings[,2]}
    score      <- GetAssayData(object = seurat.x)[features.ls[[x]],]
    to.plot    <- as.data.frame(cbind(embeddings,score))
    to.plot$modality <- x
    to.plot$cluster  <-seurat.ls[[x]]$idents_short[rownames(to.plot)] 
    to.plot$cell_barcode <- rownames(to.plot)
    to.plot$score[to.plot$score > max.cutoff] <- max.cutoff
    return(to.plot)
  })
  
}


data.ls <- FeaturePlotPaired(seurat.ls.small, features.ls,max.cutoff = 10)
data.df <- purrr::reduce(data.ls,rbind)

connections <- sample(data.ls[[1]]$cell_barcode,500)

# ggplot(data.df,aes(x=UMAP_1,y=UMAP_2)) +
#   geom_point(aes(col=cluster),size=0.1) +
#   geom_line(aes(group=cell_barcode,col=cluster),alpha=0.01) +
#   theme(panel.grid = element_blank()) #+ scale_color_viridis_c()

theme_set(theme_minimal())
col_pal <- c('grey70',viridis_pal(option = 'B')(20))

ggplot(data.df,aes(x=UMAP_1,y=UMAP_2)) +
  geom_point(aes(col=score),size=0.4) +
  geom_line(aes(group=cell_barcode),alpha=0.04,size=0.2) +
  theme(panel.grid = element_blank()) + scale_color_gradientn(colours = col_pal) + coord_cartesian(ylim=c(-3,3))
ggsave(paste0(params$out_prefix,'/figures/figure_4/Lhx2_UMAP_connected.pdf'),width=12,height = 8 )
```



```{r Irx2, fig.width=8,fig.height=8}
seurat.ls <- readRDS(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multiple_modalities/ATAC_H3K27ac_H3K27me3/seurat_multimodal/peaks/Seurat_object.Rds')
# markers <- read.csv(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multimodal_data/single_modality/H3K27ac/seurat/peaks/markers/idents_short/markers.csv')


# DimPlot(seurat.ls[[3]],group.by='idents_short',label=T) + NoLegend()

seurat.ls.small <- lapply(seurat.ls[1:3],function(x){
  x <- x[,x$idents_short %in% c("AST_TE","AST_NT")]
  x
})


# markers.ls <- lapply(seurat.ls.small,FindAllMarkers)


features.ls = list("ATAC"    = "chr13-72623831-72640434",
                   "H3K27ac" = "chr13-72621500-72643323",
                   "H3K27me3"="chr13-72621194-72642565")

FeaturePlotPaired <- function(seurat.ls,features.ls, max.cutoff =2){
  emb.ls <- lapply(names(seurat.ls),function(x){
    seurat.x   <- seurat.ls[[x]]
    embeddings <- scale(seurat.x@reductions[['umap']]@cell.embeddings)
    if(x=='H3K27ac')  {embeddings[,1] <- embeddings[,1] + 10}
    if(x=='H3K27me3') {embeddings[,1] <- embeddings[,1] + 20; embeddings[,2] <- -embeddings[,2]}
    score      <- GetAssayData(object = seurat.x)[features.ls[[x]],]
    to.plot    <- as.data.frame(cbind(embeddings,score))
    to.plot$modality <- x
    to.plot$cluster  <-seurat.ls[[x]]$idents_short[rownames(to.plot)] 
    to.plot$cell_barcode <- rownames(to.plot)
    to.plot$score[to.plot$score > max.cutoff] <- max.cutoff
    return(to.plot)
  })
  
}


data.ls <- FeaturePlotPaired(seurat.ls.small, features.ls,max.cutoff = 10)
data.df <- purrr::reduce(data.ls,rbind)

connections <- sample(data.ls[[1]]$cell_barcode,500)

# ggplot(data.df,aes(x=UMAP_1,y=UMAP_2)) +
#   geom_point(aes(col=cluster),size=0.1) +
#   geom_line(aes(group=cell_barcode,col=cluster),alpha=0.01) +
#   theme(panel.grid = element_blank()) #+ scale_color_viridis_c()

theme_set(theme_minimal())
col_pal <- c('grey70',viridis_pal(option = 'B')(20))

ggplot(data.df,aes(x=UMAP_1,y=UMAP_2)) +
  geom_point(aes(col=score),size=0.4) +
  geom_line(aes(group=cell_barcode),alpha=0.04,size=0.2) +
  theme(panel.grid = element_blank()) + scale_color_gradientn(colours = col_pal) + coord_cartesian(ylim=c(-3,3))
ggsave(paste0(params$out_prefix,'/figures/figure_4/Irx2_UMAP_connected.pdf'),width=12,height = 8 )
```




```{r Foxb1, fig.width=8,fig.height=8}
seurat.ls <- readRDS(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multiple_modalities/ATAC_H3K27ac_H3K27me3/seurat_multimodal/peaks/Seurat_object.Rds')
# markers <- read.csv(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multimodal_data/single_modality/H3K27ac/seurat/peaks/markers/idents_short/markers.csv')


# DimPlot(seurat.ls[[3]],group.by='idents_short',label=T) + NoLegend()

seurat.ls.small <- lapply(seurat.ls[1:3],function(x){
  x <- x[,x$idents_short %in% c("AST_TE","AST_NT")]
  x
})


# markers.ls <- lapply(seurat.ls.small,FindAllMarkers)


features.ls = list("ATAC"     = "chr9-69754058-69772974",
                   "H3K27ac"  = "chr9-69750612-69769655",
                   "H3K27me3" = "chr9-69751617-69782935")

FeaturePlotPaired <- function(seurat.ls,features.ls, max.cutoff =2){
  emb.ls <- lapply(names(seurat.ls),function(x){
    seurat.x   <- seurat.ls[[x]]
    embeddings <- scale(seurat.x@reductions[['umap']]@cell.embeddings)
    if(x=='H3K27ac')  {embeddings[,1] <- embeddings[,1] + 10}
    if(x=='H3K27me3') {embeddings[,1] <- embeddings[,1] + 20; embeddings[,2] <- -embeddings[,2]}
    score      <- GetAssayData(object = seurat.x)[features.ls[[x]],]
    to.plot    <- as.data.frame(cbind(embeddings,score))
    to.plot$modality <- x
    to.plot$cluster  <-seurat.ls[[x]]$idents_short[rownames(to.plot)] 
    to.plot$cell_barcode <- rownames(to.plot)
    to.plot$score[to.plot$score > max.cutoff] <- max.cutoff
    return(to.plot)
  })
  
}


data.ls <- FeaturePlotPaired(seurat.ls.small, features.ls,max.cutoff = 10)
data.df <- purrr::reduce(data.ls,rbind)

connections <- sample(data.ls[[1]]$cell_barcode,500)

# ggplot(data.df,aes(x=UMAP_1,y=UMAP_2)) +
#   geom_point(aes(col=cluster),size=0.1) +
#   geom_line(aes(group=cell_barcode,col=cluster),alpha=0.01) +
#   theme(panel.grid = element_blank()) #+ scale_color_viridis_c()

theme_set(theme_minimal())
col_pal <- c('grey70',viridis_pal(option = 'B')(20))

ggplot(data.df,aes(x=UMAP_1,y=UMAP_2)) +
  geom_point(aes(col=score),size=0.4) +
  geom_line(aes(group=cell_barcode),alpha=0.04,size=0.2) +
  theme(panel.grid = element_blank()) + scale_color_gradientn(colours = col_pal) + coord_cartesian(ylim=c(-3,3))
ggsave(paste0(params$out_prefix,'/figures/figure_4/Foxb1_UMAP_connected.pdf'),width=12,height = 8 )
```



