---
title: "R Notebook"
output: html_notebook
params:
  seurat: "/data/proj/GCB_MB/bcd_CT/single-cell/results/multiple_modalities/ATAC_H3K27ac_H3K27me3/seurat_multimodal/peaks/Seurat_object.Rds"
  seurat_WNN: "/data/proj/GCB_MB/bcd_CT/single-cell/results/multimodal_data/WNN/seurat/Seurat_object_WNN.Rds"
  out_prefix: '/data/proj/GCB_MB/bcd_CT/single-cell/results/'
---

```{r libraries}
library(Seurat)
library(Signac)
library(ggplot2)
library(RColorBrewer)
set.seed(1234)
```

```{r load_data}
seurat.ls  <- readRDS(file=params$seurat)
seurat.wnn <- readRDS(file=params$seurat_WNN)

seurat.ls <- lapply(seurat.ls[1:3],function(x){x <- AddMetaData(object = x, metadata = seurat.wnn$idents_short,col.name = 'wnn_ident_short')})
```

```{r load_markers}
markers <- read.csv(file='/data/proj/GCB_MB/bcd_CT/single-cell/results/multimodal_data/single_modality/H3K27ac/seurat/peaks/markers/idents_L3/markers_positive.csv')
head(markers)
```
```{r}
library(EnsDb.Mmusculus.v79)
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79,verbose = FALSE)
seqlevelsStyle(annotations) <- 'UCSC'

Annotation(seurat.ls[[1]]) <- annotations
Annotation(seurat.ls[[2]]) <- annotations
Annotation(seurat.ls[[3]]) <- annotations
Annotation(seurat.wnn)     <- annotations
```


```{r plot_hoxa,fig.width=6,fig.height=6}
region = 'chr6-51750000-52750000' # Hoxa

idents = c(
  'AST_TE',
  'AST_NT',
  'MGL',
  'MOL',
  'EXC1',
  'INH1'
)



cov_plot1 <- CoveragePlot(
    object = seurat.ls[['ATAC']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

cov_plot2 <- CoveragePlot(
    object = seurat.ls[['H3K27ac']],
    region = region, annotation = FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

cov_plot3 <- CoveragePlot(
    object = seurat.ls[['H3K27me3']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

gene_plot <- AnnotationPlot(
  object = seurat.ls[[1]],
  region = region
)

pdf(file = paste0(params$out_prefix,'/figures/figure_2/Hox_genes_genome_browser.pdf'),width = 12,height = 12)
CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))
dev.off()
```


```{r plot_hoxb,fig.width=12,fig.height=12}
region = 'chr11-95988899-96642912' # Hoxb

idents = c(
  'AST_TE',
  'AST_NT',
  'MGL',
  'MOL',
  'EXC1',
  'INH1'
)



cov_plot1 <- CoveragePlot(
    object = seurat.ls[['ATAC']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

cov_plot2 <- CoveragePlot(
    object = seurat.ls[['H3K27ac']],
    region = region, annotation = FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

cov_plot3 <- CoveragePlot(
    object = seurat.ls[['H3K27me3']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

gene_plot <- AnnotationPlot(
  object = seurat.ls[[1]],
  region = region
)

CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))


pdf(file = paste0(params$out_prefix,'/figures/figure_3/Hoxb_genes_genome_browser.pdf'),width = 12,height = 12)
CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))
dev.off()
```



```{r plot_hoxd,fig.width=12,fig.height=12}
region = 'chr2-73402569-75219635' # Hoxd

idents = c(
  'AST_TE',
  'AST_NT',
  'MGL',
  'MOL',
  'EXC1',
  'INH1'
)



cov_plot1 <- CoveragePlot(
    object = seurat.ls[['ATAC']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

cov_plot2 <- CoveragePlot(
    object = seurat.ls[['H3K27ac']],
    region = region, annotation = FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

cov_plot3 <- CoveragePlot(
    object = seurat.ls[['H3K27me3']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

gene_plot <- AnnotationPlot(
  object = seurat.ls[[1]],
  region = region
)

CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))


pdf(file = paste0(params$out_prefix,'/figures/figure_3/Hoxd_genes_genome_browser.pdf'),width = 12,height = 12)
CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))
dev.off()
```



```{r plot_hoxc,fig.width=12,fig.height=12}
region = 'chr15-102375974-103490727' # Hoxc

idents = c(
  'AST_TE',
  'AST_NT',
  'MGL',
  'MOL',
  'EXC1',
  'INH1'
)



cov_plot1 <- CoveragePlot(
    object = seurat.ls[['ATAC']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

cov_plot2 <- CoveragePlot(
    object = seurat.ls[['H3K27ac']],
    region = region, annotation = FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

cov_plot3 <- CoveragePlot(
    object = seurat.ls[['H3K27me3']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000))

gene_plot <- AnnotationPlot(
  object = seurat.ls[[1]],
  region = region
)

CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))


pdf(file = paste0(params$out_prefix,'/figures/figure_3/Hoxc_genes_genome_browser.pdf'),width = 12,height = 12)
CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))
dev.off()
```



```{r, fig.width=15,fig.height=15}
tile_plot <- TilePlot(
  object = seurat.ls[[2]],
  region = "chr7-45131798-45219045",
  group.by='idents_short',tile.size = 500,order.by = 'total',
)
tile_plot
```



```{r,fig.width=4,fig.height=7}
# Mag locus
region <- 'chr7-30532488-31186648'

idents = c(
  'AST_TE',
  'AST_NT',
  'MGL',
  'MOL',
  'EXC1',
  'INH1'
)
col_pal <- brewer.pal(name = 'Set2',n=length(idents))


cov_plot1 <- CoveragePlot(
    object = seurat.ls[['ATAC']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000)) + scale_fill_manual(values = col_pal)


cov_plot2 <- CoveragePlot(
    object = seurat.ls[['H3K27ac']],
    region = region, annotation = FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000)) + scale_fill_manual(values = col_pal)

cov_plot3 <- CoveragePlot(
    object = seurat.ls[['H3K27me3']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000)) + scale_fill_manual(values = col_pal)

gene_plot <- AnnotationPlot(
  object = seurat.ls[[1]],
  region = region
)


CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))



pdf(file = paste0(params$out_prefix,'/figures/figure_3/genome_browser_tracks.pdf'),width = 6,height = 10)
CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))
dev.off()
```

```{r,fig.width=2,fig.height=2}
region <- 'chr7-30888483-30951788'
tile_plot1 <- TilePlot(object = seurat.ls[['ATAC']],region=region,idents = idents,group.by = 'wnn_ident_short',tile.size = width(StringToGRanges(region))/50,tile.cells = 100,order.by = 'random')
tile_plot1 + scale_fill_gradient(low = 'white',high = 'black',guide = 'legend')

```


```{r,fig.width=2,fig.height=2}
region <- 'chr7-30888483-30951788'
tile_plot1 <- TilePlot(object = seurat.ls[['H3K27ac']],region=region,idents = idents,group.by = 'wnn_ident_short',tile.size = width(StringToGRanges(region))/50,tile.cells = 100,order.by = 'random')
tile_plot1 + scale_fill_gradient(low = 'white',high = 'black',guide = 'legend')
```

```{r,fig.width=2,fig.height=2}
region <- 'chr7-30714321-30816989'
tile_plot1 <- TilePlot(object = seurat.ls[['H3K27me3']],region=region,idents = idents,group.by = 'wnn_ident_short',tile.size = width(StringToGRanges(region))/50,tile.cells = 100,order.by = 'random')
tile_plot1 + scale_fill_gradient(low = 'white',high = 'black',guide = 'legend')
```

```{r Foxg1 plot,fig.width=4,fig.height=7}
region <- 'chr12-49370426-49407415'

idents = c(
  'AST_TE',
  'AST_NT'
)

col_pal <- brewer.pal(name = 'Set2',n=3)


cov_plot1 <- CoveragePlot(
    object = seurat.ls[['ATAC']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000),extend.upstream = 10000,extend.downstream = 10000) + scale_fill_manual(values = col_pal)

cov_plot2 <- CoveragePlot(
    object = seurat.ls[['H3K27ac']],
    region = region, annotation = FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000),extend.upstream = 10000,extend.downstream = 10000)+ scale_fill_manual(values = col_pal)

cov_plot3 <- CoveragePlot(
    object = seurat.ls[['H3K27me3']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000),extend.upstream = 10000,extend.downstream = 10000)+ scale_fill_manual(values = col_pal)

gene_plot <- AnnotationPlot(
  object = seurat.ls[[1]],
  region = region
)


CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))

pdf(file = paste0(params$out_prefix,'/figures/figure_4/genome_browser_Foxg1.pdf'),width = 6,height = 10)
CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))
dev.off()


```



```{r Irx2 plot,fig.width=4,fig.height=7}
region <- 'chr13-72571202-72724468'

idents = c(
  'AST_TE',
  'AST_NT'
)

col_pal <- brewer.pal(name = 'Set2',n=3)


cov_plot1 <- CoveragePlot(
    object = seurat.ls[['ATAC']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000),extend.upstream = 10000,extend.downstream = 10000) + scale_fill_manual(values = col_pal)

cov_plot2 <- CoveragePlot(
    object = seurat.ls[['H3K27ac']],
    region = region, annotation = FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000),extend.upstream = 10000,extend.downstream = 10000)+ scale_fill_manual(values = col_pal)

cov_plot3 <- CoveragePlot(
    object = seurat.ls[['H3K27me3']],
    region = region, annotation=FALSE,
    peaks = FALSE,group.by = 'wnn_ident_short',idents = idents,
    window = floor(width(StringToGRanges(region))/1000),extend.upstream = 10000,extend.downstream = 10000)+ scale_fill_manual(values = col_pal)

gene_plot <- AnnotationPlot(
  object = seurat.ls[[1]],
  region = region
)


CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))

pdf(file = paste0(params$out_prefix,'/figures/figure_4/genome_browser_Irx2.pdf'),width = 6,height = 10)
CombineTracks(list(cov_plot1,cov_plot2,cov_plot3,gene_plot), heights = c(1,1,1,1))
dev.off()


```



